name: Pull Request Deployment
on: pull_request
jobs:
  deploy:
    # name: OpenShift Deployment
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #   - name: Use Pipeline Action
    #     uses: bcgov/openshift-launchpad-deployment@master
    #     with:
    #       MODE: client
    #       AUTH_TOKEN: ${{ secrets.action_token }}
    #       NAMESPACE: auzhsi-dev
    #       APP_NAME: wps-web-pr-${{ github.event.number }}
    #       BRANCH: ${{ github.event.pull_request.head.ref }}
    #       CLIENT_PORT: 3000

    name: OpenShift Deployment Using GH Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Pipeline Action
        uses: bcgov/openshift-launchpad-deployment@custom-script
        with:
          MODE: server
          AUTH_TOKEN: ${{ secrets.action_token }}
          NAMESPACE: auzhsi-tools
          APP_NAME: wps-web-pr$-{{ github.event.number }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          SCRIPT: openshift/scripts/oc_build.sh pr-57