name: Pull Request Build & Deployment with scripts

on:
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run test:ci

  build_and_deploy:
    name: OpenShift Deployment Using GH Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        uses: bcgov/openshift-launchpad-deployment@custom-script
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: openshift/scripts/oc_build.sh pr-${{ github.event.number }} apply

      - name: Deploy to Dev
        uses: bcgov/openshift-launchpad-deployment@custom-script
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: openshift/scripts/oc_deploy.sh pr-${{ github.event.number }} apply