# Provide post-merge (prod, test, demo) instructions in with a comment
#
# Triggers on PR close, but only comments if merged==true
#
name: Post-merge Comment

on:
  pull_request:
    types: [opened]

jobs:
  variables:
    name: Comment on Merged Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for your contribution!  Please see CONTRIBUTING.md for details.  \nIMPORTANT: When merged a persistent deployment will begin at the following link:  https://github.com/bcgov/wps-web/actions?query=workflow%3A%22Post-merge+Rollout%22'
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
