name: PRE-MASTER

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        shell: bash
        run: |
          echo "::set-env name=SUFFIX::pre-master"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: GIT_BRANCH=pre-master openshift/scripts/oc_build.sh ${SUFFIX} apply
        if: ${{env.GITHUB_HEAD_REF}} == 'pre-master'

      - name: Deploy to Dev
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: PROJ_PROD=auzhsi-test openshift/scripts/oc_deploy.sh ${SUFFIX} apply
        if: ${{env.GITHUB_HEAD_REF}} == 'pre-master'
      
      - name: Promote Image
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: TAG_PRODopenshift/scripts/oc_promote.sh ${SUFFIX} apply
        if: ${{env.GITHUB_HEAD_REF}} == 'pre-master'
