# Post-merge or push build for a DEMO instance in auzhsi-test
#
name: DEMO

on:
  push:
    branches:
      - demo

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: GIT_BRANCH=demo openshift/scripts/oc_build.sh demo apply

      - name: Deploy to Test
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          AUTH_TOKEN: ${{ secrets.action_token }}
          SCRIPT: PROJ_DEV=auzhsi-test openshift/scripts/oc_deploy.sh demo apply